CREATE TABLE projects (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	is_system BOOLEAN NOT NULL DEFAULT FALSE,
	status VARCHAR(16) NOT NULL DEFAULT 'PLANNED',
	priority INTEGER NOT NULL DEFAULT 0,
	favorite BOOLEAN NOT NULL DEFAULT FALSE,
	status_before_archive VARCHAR(16),
	archived_at TIMESTAMP,
	archive_reason TEXT NOT NULL DEFAULT '',
	progress_summary TEXT NOT NULL DEFAULT '',
	next_step TEXT NOT NULL DEFAULT '',
	blockers TEXT NOT NULL DEFAULT '',
	start_command TEXT NOT NULL DEFAULT '',
	build_command TEXT NOT NULL DEFAULT '',
	technical_decisions TEXT NOT NULL DEFAULT '',
	context_updated_at TIMESTAMP,
	repository_url VARCHAR(2048) NOT NULL DEFAULT '',
	deployment_url VARCHAR(2048) NOT NULL DEFAULT '',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT projects_status_check CHECK (status IN ('PLANNED', 'ACTIVE', 'PAUSED', 'ARCHIVED')),
	CONSTRAINT projects_priority_check CHECK (priority BETWEEN 0 AND 3)
);

CREATE TABLE repository_metadata (
	project_id BIGINT PRIMARY KEY,
	provider VARCHAR(32) NOT NULL,
	owner_name VARCHAR(255) NOT NULL DEFAULT '',
	repository_name VARCHAR(255) NOT NULL DEFAULT '',
	canonical_url VARCHAR(2048) NOT NULL DEFAULT '',
	default_branch VARCHAR(255) NOT NULL DEFAULT '',
	last_commit_sha VARCHAR(255) NOT NULL DEFAULT '',
	last_commit_message TEXT NOT NULL DEFAULT '',
	last_commit_author VARCHAR(255) NOT NULL DEFAULT '',
	last_commit_at TIMESTAMP,
	readme_file_name VARCHAR(255) NOT NULL DEFAULT '',
	readme_content TEXT NOT NULL DEFAULT '',
	languages_json TEXT NOT NULL DEFAULT '{}',
	sync_status VARCHAR(32) NOT NULL DEFAULT 'NEVER_SYNCED',
	last_attempt_at TIMESTAMP,
	last_successful_sync_at TIMESTAMP,
	error_code VARCHAR(64) NOT NULL DEFAULT '',
	error_message TEXT NOT NULL DEFAULT '',
	branches_url VARCHAR(2048) NOT NULL DEFAULT '',
	issues_url VARCHAR(2048) NOT NULL DEFAULT '',
	pull_requests_url VARCHAR(2048) NOT NULL DEFAULT '',
	CONSTRAINT repository_metadata_project_fk
		FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE project_links (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL,
	label VARCHAR(255) NOT NULL,
	url VARCHAR(2048) NOT NULL,
	link_order INTEGER NOT NULL,
	CONSTRAINT project_links_project_fk
		FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
	CONSTRAINT project_links_project_order_unique UNIQUE (project_id, link_order)
);

CREATE TABLE notes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT notes_project_fk
		FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE code_snippets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL,
	title VARCHAR(255) NOT NULL,
	language VARCHAR(100) NOT NULL DEFAULT 'text',
	source_code TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT code_snippets_project_fk
		FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE tags (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE todos (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL DEFAULT '',
	completed BOOLEAN NOT NULL DEFAULT FALSE,
	completed_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT todos_project_fk
		FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE ideas (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL DEFAULT '',
	converted BOOLEAN NOT NULL DEFAULT FALSE,
	converted_todo_id BIGINT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT ideas_project_fk
		FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
	CONSTRAINT ideas_converted_todo_fk
		FOREIGN KEY (converted_todo_id) REFERENCES todos(id) ON DELETE SET NULL
);

CREATE TABLE idea_tags (
	idea_id BIGINT NOT NULL,
	tag_id BIGINT NOT NULL,
	CONSTRAINT idea_tags_idea_fk
		FOREIGN KEY (idea_id) REFERENCES ideas(id) ON DELETE CASCADE,
	CONSTRAINT idea_tags_tag_fk
		FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
	CONSTRAINT idea_tags_unique UNIQUE (idea_id, tag_id)
);

CREATE TABLE todo_tags (
	todo_id BIGINT NOT NULL,
	tag_id BIGINT NOT NULL,
	CONSTRAINT todo_tags_todo_fk
		FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE,
	CONSTRAINT todo_tags_tag_fk
		FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
	CONSTRAINT todo_tags_unique UNIQUE (todo_id, tag_id)
);

CREATE INDEX notes_project_id_idx ON notes(project_id);
CREATE INDEX code_snippets_project_id_idx ON code_snippets(project_id);
CREATE INDEX project_links_project_id_idx ON project_links(project_id);
CREATE INDEX projects_status_idx ON projects(status);
CREATE INDEX projects_priority_idx ON projects(priority);
CREATE INDEX todos_project_id_idx ON todos(project_id);
CREATE INDEX ideas_project_id_idx ON ideas(project_id);
CREATE INDEX idea_tags_tag_id_idx ON idea_tags(tag_id);
CREATE INDEX todo_tags_tag_id_idx ON todo_tags(tag_id);
