CREATE TABLE entity_references (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	source_type VARCHAR(16) NOT NULL,
	source_id BIGINT NOT NULL,
	target_type VARCHAR(16) NOT NULL,
	target_id BIGINT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT entity_references_unique UNIQUE (source_type, source_id, target_type, target_id),
	CONSTRAINT entity_references_source_type_check CHECK (source_type IN ('PROJECT', 'NOTE', 'SNIPPET', 'IDEA', 'TODO')),
	CONSTRAINT entity_references_target_type_check CHECK (target_type IN ('PROJECT', 'NOTE', 'SNIPPET', 'IDEA', 'TODO'))
);

CREATE INDEX entity_references_source_idx ON entity_references(source_type, source_id);
CREATE INDEX entity_references_target_idx ON entity_references(target_type, target_id);

CREATE INDEX notes_updated_at_idx ON notes(updated_at);
CREATE INDEX code_snippets_updated_at_idx ON code_snippets(updated_at);
CREATE INDEX ideas_updated_at_idx ON ideas(updated_at);
CREATE INDEX todos_updated_at_idx ON todos(updated_at);
CREATE INDEX projects_updated_at_idx ON projects(updated_at);
CREATE INDEX notes_title_idx ON notes(title);
CREATE INDEX code_snippets_title_idx ON code_snippets(title);
CREATE INDEX ideas_title_idx ON ideas(title);
CREATE INDEX todos_title_idx ON todos(title);
CREATE INDEX projects_name_idx ON projects(name);
