CREATE TABLE app_users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	oidc_subject VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL DEFAULT '',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT app_users_subject_unique UNIQUE (oidc_subject)
);

-- Everything created before multi-user support belongs to this account. It is the only
-- row at this point, so the backfills below can simply select it.
INSERT INTO app_users (oidc_subject, username) VALUES ('${legacyOwnerSubject}', '');

ALTER TABLE projects ADD COLUMN owner_id BIGINT;
UPDATE projects SET owner_id = (SELECT id FROM app_users);
ALTER TABLE projects ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE projects ADD CONSTRAINT projects_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users(id);
-- Target of the composite foreign keys below, which keep an entry inside its owner's projects.
ALTER TABLE projects ADD CONSTRAINT projects_id_owner_unique UNIQUE (id, owner_id);
CREATE INDEX projects_owner_idx ON projects(owner_id, status);

ALTER TABLE notes ADD COLUMN owner_id BIGINT;
UPDATE notes SET owner_id = (SELECT id FROM app_users);
ALTER TABLE notes ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE notes ADD CONSTRAINT notes_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users(id);
ALTER TABLE notes DROP CONSTRAINT notes_project_fk;
ALTER TABLE notes ADD CONSTRAINT notes_project_fk
	FOREIGN KEY (project_id, owner_id) REFERENCES projects(id, owner_id) ON DELETE CASCADE;
CREATE INDEX notes_owner_idx ON notes(owner_id, project_id);

ALTER TABLE code_snippets ADD COLUMN owner_id BIGINT;
UPDATE code_snippets SET owner_id = (SELECT id FROM app_users);
ALTER TABLE code_snippets ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE code_snippets ADD CONSTRAINT code_snippets_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users(id);
ALTER TABLE code_snippets DROP CONSTRAINT code_snippets_project_fk;
ALTER TABLE code_snippets ADD CONSTRAINT code_snippets_project_fk
	FOREIGN KEY (project_id, owner_id) REFERENCES projects(id, owner_id) ON DELETE CASCADE;
CREATE INDEX code_snippets_owner_idx ON code_snippets(owner_id, project_id);

ALTER TABLE ideas ADD COLUMN owner_id BIGINT;
UPDATE ideas SET owner_id = (SELECT id FROM app_users);
ALTER TABLE ideas ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE ideas ADD CONSTRAINT ideas_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users(id);
ALTER TABLE ideas DROP CONSTRAINT ideas_project_fk;
ALTER TABLE ideas ADD CONSTRAINT ideas_project_fk
	FOREIGN KEY (project_id, owner_id) REFERENCES projects(id, owner_id) ON DELETE CASCADE;
CREATE INDEX ideas_owner_idx ON ideas(owner_id, project_id);

ALTER TABLE todos ADD COLUMN owner_id BIGINT;
UPDATE todos SET owner_id = (SELECT id FROM app_users);
ALTER TABLE todos ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE todos ADD CONSTRAINT todos_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users(id);
ALTER TABLE todos DROP CONSTRAINT todos_project_fk;
ALTER TABLE todos ADD CONSTRAINT todos_project_fk
	FOREIGN KEY (project_id, owner_id) REFERENCES projects(id, owner_id) ON DELETE CASCADE;
CREATE INDEX todos_owner_idx ON todos(owner_id, project_id);

-- Tag names become unique per owner. The old constraint was declared inline and has no
-- portable name, so the column is replaced, which takes the constraint with it.
ALTER TABLE tags ADD COLUMN owner_id BIGINT;
UPDATE tags SET owner_id = (SELECT id FROM app_users);
ALTER TABLE tags ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE tags ADD CONSTRAINT tags_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users(id);
ALTER TABLE tags ADD COLUMN tag_name VARCHAR(100);
UPDATE tags SET tag_name = name;
ALTER TABLE tags DROP COLUMN name;
ALTER TABLE tags RENAME COLUMN tag_name TO name;
ALTER TABLE tags ALTER COLUMN name SET NOT NULL;
ALTER TABLE tags ADD CONSTRAINT tags_owner_name_unique UNIQUE (owner_id, name);

ALTER TABLE entity_references ADD COLUMN owner_id BIGINT;
UPDATE entity_references SET owner_id = (SELECT id FROM app_users);
ALTER TABLE entity_references ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE entity_references ADD CONSTRAINT entity_references_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users(id);
CREATE INDEX entity_references_owner_idx ON entity_references(owner_id);

-- One token per provider and owner. The primary key was declared inline as well, so the
-- table is rebuilt; it has no identity column that would need carrying over.
CREATE TABLE git_credentials_new (
	owner_id BIGINT NOT NULL,
	provider VARCHAR(32) NOT NULL,
	label VARCHAR(255) NOT NULL DEFAULT '',
	host VARCHAR(255) NOT NULL DEFAULT '',
	token_encrypted TEXT NOT NULL,
	token_hint VARCHAR(16) NOT NULL DEFAULT '',
	account_login VARCHAR(255) NOT NULL DEFAULT '',
	scopes VARCHAR(1024) NOT NULL DEFAULT '',
	status VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED',
	last_error TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_verified_at TIMESTAMP,
	CONSTRAINT git_credentials_owner_provider_pk PRIMARY KEY (owner_id, provider),
	CONSTRAINT git_credentials_owner_fk FOREIGN KEY (owner_id) REFERENCES app_users(id)
);
INSERT INTO git_credentials_new
	(owner_id, provider, label, host, token_encrypted, token_hint, account_login, scopes,
		status, last_error, created_at, last_verified_at)
	SELECT (SELECT id FROM app_users), provider, label, host, token_encrypted, token_hint,
		account_login, scopes, status, last_error, created_at, last_verified_at
	FROM git_credentials;
DROP TABLE git_credentials;
ALTER TABLE git_credentials_new RENAME TO git_credentials;
ALTER TABLE git_credentials ADD CONSTRAINT git_credentials_provider_check CHECK (provider IN ('GITHUB', 'GITLAB'));
ALTER TABLE git_credentials ADD CONSTRAINT git_credentials_status_check
	CHECK (status IN ('VERIFIED', 'INVALID', 'UNREADABLE', 'UNVERIFIED'));
