spring.application.name=backend
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/devhub}
spring.datasource.username=${DATABASE_USERNAME:devhub}
spring.datasource.password=${DATABASE_PASSWORD:devhub}

management.endpoint.health.probes.enabled=true
